### PR TITLE
Project conception kochin part and fix issue in content list

### PR DESCRIPTION
**Pull request by ivankochin**
Push content of "Project needed" part for "Project Conception" document
Fix issue in content list : add right numbers order

### CODE REVIEW

**Comment by ivankochin** [comment]
@Zemlyanskiy
@Iv-Umlore
@MaksimenkoAN

Guys, please review this request as soon as posible
I will be glad to discuss any comments
Feel free to ask any questions.

**Comment by Zemlyanskiy** [comment]
+1

**Comment by Zemlyanskiy** [comment]
+1!

**Comment by Zemlyanskiy** [comment]
:+1:

**Comment by MaksimenkoAN** [comment]
👍

**Comment by Iv-Umlore** [comment]
+1

**Comment by Iv-Umlore** [comment]
:+1:

**Pull request merged**
